In [2]:
import tensorflow as tf

In [3]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

In [4]:
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [5]:
num=[1,2,3,4,5,6]


In [16]:
num1=[[1,2,3], [4,5,6]]

In [17]:
tf2=tf.convert_to_tensor(num1)

In [21]:
tf2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [6]:
tf1=tf.convert_to_tensor(num)

In [12]:
tf1=tf1*2

In [13]:
tf1

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12])>

In [14]:
tensor = tf.constant([
    [
        [1,2,3]
    ],
    [
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
])

In [15]:
tensor

<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])>